apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nfsminios.k8.krmelj.xyz
spec:
  group: k8.krmelj.xyz
  names:
    kind: NFSMinio
    listKind: NFSMinioList
    plural: nfsminios
    singular: nfsminio
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            domain:
              type: string
            nfs:
              properties:
                path:
                  type: string
                readOnly:
                  type: boolean
                server:
                  type: string
              required:
              - server
              - path
              - readOnly
              type: object
            username:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
          required:
          - username
          - nfs
          - domain
          type: object
        status:
          properties:
            secretKeyHash:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: byte
              type: string
          required:
          - secretKeyHash
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
