apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-minio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nfs-minio-operator
  template:
    metadata:
      labels:
        name: nfs-minio-operator
    spec:
      serviceAccountName: nfs-minio-operator
      containers:
        - name: nfs-minio-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - nfs-minio-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nfs-minio-operator"
