// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinio":       schema_pkg_apis_k8_v1alpha1_NFSMinio(ref),
		"github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioSpec":   schema_pkg_apis_k8_v1alpha1_NFSMinioSpec(ref),
		"github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioStatus": schema_pkg_apis_k8_v1alpha1_NFSMinioStatus(ref),
	}
}

func schema_pkg_apis_k8_v1alpha1_NFSMinio(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NFSMinio is the Schema for the nfsminios API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioSpec", "github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_k8_v1alpha1_NFSMinioSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NFSMinioSpec defines the desired state of NFSMinio",
				Properties: map[string]spec.Schema{
					"username": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"nfs": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioSpecNFS"),
						},
					},
					"domain": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"username", "nfs", "domain"},
			},
		},
		Dependencies: []string{
			"github.com/greenstatic/nfs-minio-operator/pkg/apis/k8/v1alpha1.NFSMinioSpecNFS"},
	}
}

func schema_pkg_apis_k8_v1alpha1_NFSMinioStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "NFSMinioStatus defines the observed state of NFSMinio",
				Properties: map[string]spec.Schema{
					"secretKeyHash": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html",
							Type:        []string{"string"},
							Format:      "byte",
						},
					},
				},
				Required: []string{"secretKeyHash"},
			},
		},
		Dependencies: []string{},
	}
}
