name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone operator-sdk git repository
      run: go get -d github.com/operator-framework/operator-sdk
    - name: Install
      run: cd $GOPATH/src/github.com/operator-framework/operator-sdk && git checkout master && make tidy && make install
    - name: Build Docker image
      run: operator-sdk build greenstatic/nfs-minio-operatorexample/memcached-operator:latest # TODO: change tag
    - name: Push image to Docker Hub
      run: docker push greenstatic/nfs-minio-operatorexample/memcached-operator:latest
